add_newline = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
error_symbol = "âœ—"

[directory]
style = "#369DE3"
truncation_length = 0
truncate_to_repo = false

[git_state]
# progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_branch]
style = "#FFFF99"
symbol = "ğŸŒ± "
truncation_symbol = ""

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++$count](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

[java]
symbol = "ğŸŒŸ "
[scala]
symbol = "ğŸŒŸ "

[ruby]
symbol = "ğŸ’ "

[golang]
format = "via [ğŸğŸ’¨ $version](bold cyan) "

[nodejs]
format = "via [ğŸ¤– $version](bold green) "

[python]
symbol = "ğŸ‘¾ "
pyenv_version_name = true

[rust]
format = "via [ğŸ¦€ $version](red bold)"

[ocaml]
symbol = "ğŸª "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[package]
symbol = "ğŸ "

[aws]
format = 'on [$symbol$profile(\($region\))]($style) '
style = "bold blue"
symbol = "ğŸ…° "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[cmake]
format = "via CMake "